version: "3.9"
services:
  pin_db:
    container_name: auth_db
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: auth_example
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
    healthcheck:
      test: pg_isready -U postgres -d auth_example
      interval: 10s
      timeout: 3s
      retries: 3
    mem_limit: 4g
    shm_size: 1g
